### ISSUE TITLE
Possible missing dependency between namespace and retention policy

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-container-registry#128]
from consumer: "state rm the retention policy because namespace has been deleted before the retention policy"

possibly due to the fact that the implicit dependency is on the name, which is an input, so not computed

 https://github.com/terraform-ibm-modules/terraform-ibm-container-registry/blob/84b37d897ea402d2ee69c2675c279b3730ffbf8b/main.tf#L9

### Affected modules

*

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Fixed in https://github.com/terraform-ibm-modules/terraform-ibm-container-registry/pull/155
